# example netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  
[[redirects]]
  from = "http://dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true
