# example netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/"
  status = 200

[[redirects]]
  from = "/help"
  to = "/help"
  status = 200

[[redirects]]
  from = "/api-connect"
  to = "/api-connect"
  status = 200

[[redirects]]
  from = "/strategy"
  to = "/strategy"
  status = 200
