# example netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true
  conditions = { Domain = "www.dokkanbattlebuilder.com" }